spring:
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: bicis-service
          uri: lb://bicis-service
          predicates:
            - Path=/api/bicis/**
          filters:
            - StripPrefix=2
        - id: viaje-service
          uri: lb://viaje-service
          predicates:
            - Path=/api/travel/**
          filters:
            - StripPrefix=2
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=2